version: "3.3"

services:
  agilitymanager_nginx:
    image: nginx:latest
    container_name: agilitymanager_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
    depends_on:
      - agilitymanager_web
    restart: "on-failure"
  agilitymanager_web:
    container_name: agilitymanager_web
    image: kdejesoftware/agilitymanager:latest
    command: bash -c '
        cd src &&
        python manage.py migrate &&
        python manage.py compilemessages &&
        python manage.py collectstatic --noinput &&
        gunicorn agilitymanager.wsgi:application --bind 0.0.0.0:8000
      '
    environment:
      - "DEFAULT_SUPERUSER_PASSWORD=admin"
      - "ALLOWED_HOSTS=*"
      - "DATABASE_NAME=agilitymanager"
      - "DATABASE_USER=agilitymanager"
      - "DATABASE_PASSWORD=admin"
      - "DATABASE_HOST=agilitymanager_db"
      - "API_SERVER=https://zarascope.agilitymanager.com"
      - "REDIS_SERVER=redis://redis:6379"
    depends_on:
      - agilitymanager_db
  agilitymanager_db:
    container_name: agilitymanager_db
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - agilitymanager_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_USER=agilitymanager"
      - "POSTGRES_DB=agilitymanager"
  agilitymanager_pgadmin:
    container_name: agilitymanager_pgadmin
    image: dpage/pgadmin4:7.5
    # restart: always
    volumes:
      - ./pgconfig:/pgconfig
      - agilitymanager_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agilitymanager.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgconfig/servers.json
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 10
    ports:
      - "5050:80"
volumes:
  agilitymanager_data:
  agilitymanager_pgadmin: