services:
  
  cache:
    image: redis:6.2-alpine
    container_name: ${STACK_NAME}_redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
  
  nginx:
    image: nginx:latest
    container_name: ${STACK_NAME}_nginx
    ports:
      - ${NGINX_PUBLIC_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
    depends_on:
      - web
    restart: "always"
  
  web:
    container_name: ${STACK_NAME}_web
    image: kdejesoftware/agilitymanager:2.0.14
    command: bash -c '
        cd src &&
        ./run.sh
      '
    environment:
      DEFAULT_SUPERUSER_PASSWORD: ${ADMIN_PASSWORD}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      API_SERVER: ${API_SERVER}
      ASYNC_ENABLED: ${ASYNC_ENABLED}
    depends_on:
      - db
    restart: "always"
  
  db:
    container_name: ${STACK_NAME}_db
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: "always"
  
  pgadmin:
    container_name: ${STACK_NAME}_pgadmin
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./pgconfig:/pgconfig
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_SERVER_JSON_FILE: /pgconfig/servers.json
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 10
    ports:
      - ${PGADMIN_PUBLIC_PORT}:80

volumes:
  data: